### PR TITLE
Change Strong tag to Markdown syntax in doc comment

### PR DESCRIPTION
**Pull request by jbl428**
# Motivation:

I have found out there are some typo in comments. 
I think we can use markdown instead of correcting typo :)

# Modifications:

- Change `<strong>` tags to markdown syntax in comment.
- Remove unused import
- lint some test code

### CODE REVIEW

**Comment by cj848** [comment]
Once I checked the wrong part with <string>
It is true that there is a typo, but why did you change it to markdown?

And it is commented as strong in MultiSelectDsl as well. If it is modified, it should be processed together.

-- korean
일단 <string> 으로 잘못된 부분을 확인했습니다
오타가 난것은 맞는데 markdown 으로 바꾼 이유는 무엇일까요?

그리고 MultiSelectDsl 에도 마찬가지로 strong 으로 comment 가 되어 있습니다. 수정한다면 같이 처리 되어야 합니다.

**Comment by jbl428** [comment]
> It is true that there is a typo, but why did you change it to markdown?

I have changed markdown because `KDoc` support `Markdown` and it has simpler form.
link: https://kotlinlang.org/docs/kotlin-doc.html#inline-markup

If there are some reason to use HTML, we can still use it. 😄 

> And it is commented as strong in MultiSelectDsl as well. If it is modified, it should be processed together.

I will change that code too if it is OK to use `Markdown`.

**Comment by cj848** [comment]
Now I know that kdoc had a part where the markdown syntax was applied. 
Thank you for good information. 
The jdsl team has no disagreements. 
As mentioned above, please fix the unprocessed MultiSelectDsl as well.

-- korean
kdoc 에 markdown 문법이 적용되는 부분이 있었다는 걸 이제 알았습니다. 
좋은 정보 감사합니다. 
jdsl 팀은 이견이 없습니다. 
위에 언급된 대로 처리 되지 않은 MultiSelectDsl 같이 수정 부탁드립니다.

**Review by cj848 — APPROVED** [review]

**Comment by cj848** [comment]
There is a part where a compilation error occurs, please check it once.

-- korean
컴파일 오류 나는 부분이 있는데 한번 체크 부탁드립니다.

**Comment by jbl428** [comment]
Done, I checked that test passes in my forked repo

https://github.com/jbl428/kotlin-jdsl/runs/6258979777?check_suite_focus=true

**Review by cj848 — APPROVED** [review]

**Review by shouwn — APPROVED** [review]

**Review by pickmoment — APPROVED** [review]

**Review by huisam — APPROVED** [review]

**Pull request merged**
