### PR TITLE
[ISSUE-708] change @Transactional readOnly for select query

### LINKED ISSUE #708: [Question] KotlinJdslJpqlExecutor interface functions
## Question 1
I wonder why are the generic types of all lists returned in KotlinJdslJpqlExecutor are all nullable var??
is there something reason???
cuz it would be useful to add not null list functions rather than only function nullable list return

image

## Question 2

KotlinJdslJpqlExecutorImpl class has Transactional annotation but `readOnly` is false
but I think that `findAll`, `findPage` ... etc  functions should be readOnly true

### PR DESCRIPTION
**Pull request by kihwankim**
# Motivation

- in spring data jpa SimpleJpaRepository class declare `@Transactional` but in select query they put readOnly true

# Modifications

- spring data KotlinJdslJpqlExecutor class's `@Transactional` readOnly option changed(false -> true) for select query

# Result

- in select query readOnly option changed true -> false

# Closes

- closes #708

### CODE REVIEW

**Review by cj848 — APPROVED** [review]

**Comment by shouwn** [comment]
Did you create a PR on the main branch because you think this change should be released as a hotfix?

If not, please change the base branch to the develop branch.

**Comment by kihwankim** [comment]
@shouwn I chanted

**Comment by shouwn** [comment]
@kihwankim Thanks for the change. 

The branch change caused a conflict, please check it out or create a new PR.

**Comment by kihwankim** [comment]
@shouwn  I created new pr #710
plz check it

**Pull request closed without merging**
